# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 10:08
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='children',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='operations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pur', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z@.]*$', 'Only alphanumeric characters are allowed.')])),
                ('aadharhof', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z@.]*$', 'Only alphanumeric characters are allowed.')])),
                ('mobile', models.IntegerField(validators=[django.core.validators.MinLengthValidator(10)])),
                ('date', models.DateField(default=datetime.datetime(2017, 8, 17, 10, 8, 5, 75472, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('aadharid', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z@.]*$', 'Only alphanumeric characters are allowed.')])),
                ('email', models.CharField(max_length=20, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z@.]*$', 'Only Email characters are allowed.')])),
            ],
        ),
        migrations.AddField(
            model_name='children',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile'),
        ),
    ]
