# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 10:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operations',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 8, 17, 10, 13, 32, 391416, tzinfo=utc)),
        ),
    ]
