# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 10:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20170817_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='qualifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='doctorid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Others')], default=3, max_length=6),
        ),
        migrations.AddField(
            model_name='profile',
            name='nationality',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='operations',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 8, 17, 10, 51, 45, 945556, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='qualifications',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile'),
        ),
    ]
