# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 10:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20170817_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='doctorid',
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default=1, max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operations',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 8, 17, 10, 56, 12, 124953, tzinfo=utc)),
        ),
    ]
