# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 10:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20170817_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='operations',
            name='username',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='operations',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 8, 17, 10, 58, 51, 868373, tzinfo=utc)),
        ),
    ]
