# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 12:49
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20170817_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='operations',
            name='bhamasahof',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AddField(
            model_name='operations',
            name='filename',
            field=models.CharField(max_length=100, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='operations',
            name='aadharhof',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='operations',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 8, 17, 12, 49, 56, 431830, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='operations',
            name='pur',
            field=models.CharField(max_length=14, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
    ]
