# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 14:59
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20170817_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='operations',
            name='hospital',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='operations',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 8, 17, 14, 59, 57, 378891, tzinfo=utc)),
        ),
    ]
