# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 18:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20170817_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operations',
            name='filename',
        ),
        migrations.AlterField(
            model_name='operations',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 8, 17, 18, 38, 24, 312202, tzinfo=utc)),
        ),
    ]
