# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 19:06
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_auto_20170817_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operations',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 8, 17, 19, 6, 54, 277665, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='operations',
            name='pur',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
    ]
